// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkpdfzzlrircingvbjjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcGRmenpscmlyY2luZ3ZiampqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTIxNjMsImV4cCI6MjA1NzQ2ODE2M30.WOfJ5uWns1gY2BGMRBG-M7Ilk1HrO7N-idwGAZ3xwbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);